/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loginregisterdb;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.time.format.DateTimeFormatter;  
import java.time.LocalDateTime;   
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Acer
 */
public class index extends javax.swing.JFrame {
    static String idSession;
    static String iduSession;
    /**
     * Creates new form index
     */
    public index() {
        initComponents();
        if(loginMain.getAkses().equals("1")){
            try{
                Connection conn = koneksi.configDB();
                Statement s = conn.createStatement();
                String sql = "SELECT * FROM user WHERE username = '"+loginMain.getUname()+"'";
                ResultSet rs = s.executeQuery(sql);
                if(rs.next()){
                    iduSession = rs.getString("id_user");
                    uname.setText(rs.getString("username").toUpperCase());
                    namaLengkap.setText(rs.getString("nama_lengkap"));
                    kelas.setText(rs.getString("kelas").toUpperCase());
                    noTelp.setText(rs.getString("no_telp").toUpperCase());
                    alamat.setText(rs.getString("alamat"));
                }

            }catch(Exception e){
//                JOptionPane.showMessageDialog(null, "GAGAL DISIMPAN, error di : "+e);
            }
            cekIsi();
        }
        else if(loginMain.getAkses().equals("2")){
            try{
                Connection conn = koneksi.configDB();
                Statement s = conn.createStatement();
                String sql = "SELECT * FROM guru WHERE username = '"+loginMain.getUname()+"'";
                ResultSet rs = s.executeQuery(sql);
                if(rs.next()){
                    idSession = rs.getString("id_guru");
                    uname.setText(rs.getString("username").toUpperCase());
                    namaLengkap.setText(rs.getString("nama_lengkap"));
                    kelas.setText(rs.getString("jabatan").toUpperCase());
                    noTelp.setText(rs.getString("no_telp").toUpperCase());
                    alamat.setText(rs.getString("alamat"));
                }

            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "GAGAL DISIMPAN, error di : "+e);
            }
            cekIsi();
        }
        
        test();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        uname = new javax.swing.JLabel();
        namaLengkap_label = new javax.swing.JLabel();
        namaLengkap = new javax.swing.JTextField();
        kelas = new javax.swing.JTextField();
        namaLengkap_label2 = new javax.swing.JLabel();
        noTelp = new javax.swing.JTextField();
        namaLengkap_label3 = new javax.swing.JLabel();
        alamat = new javax.swing.JTextField();
        namaLengkap_label5 = new javax.swing.JLabel();
        buatTugas = new javax.swing.JButton();
        tambahTugas = new javax.swing.JButton();
        absen = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        kembali = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 255, 204));
        setMinimumSize(new java.awt.Dimension(720, 420));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setForeground(new java.awt.Color(51, 102, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(720, 420));
        jPanel1.setMinimumSize(new java.awt.Dimension(720, 420));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        uname.setFont(new java.awt.Font("Oswald", 1, 30)); // NOI18N
        uname.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 11, 160, 39));

        namaLengkap_label.setFont(new java.awt.Font("Oswald", 1, 24)); // NOI18N
        namaLengkap_label.setForeground(new java.awt.Color(255, 255, 255));
        namaLengkap_label.setText("NAMA LENGKAP");
        jPanel1.add(namaLengkap_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 124, 176, -1));

        namaLengkap.setBorder(null);
        namaLengkap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaLengkapActionPerformed(evt);
            }
        });
        jPanel1.add(namaLengkap, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, 530, 32));

        kelas.setBorder(null);
        kelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelasActionPerformed(evt);
            }
        });
        jPanel1.add(kelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 242, 530, 40));

        namaLengkap_label2.setFont(new java.awt.Font("Oswald", 1, 24)); // NOI18N
        namaLengkap_label2.setForeground(new java.awt.Color(255, 255, 255));
        namaLengkap_label2.setText("KELAS");
        jPanel1.add(namaLengkap_label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 200, 176, -1));

        noTelp.setBorder(null);
        noTelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noTelpActionPerformed(evt);
            }
        });
        jPanel1.add(noTelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, 530, 40));

        namaLengkap_label3.setFont(new java.awt.Font("Oswald", 1, 24)); // NOI18N
        namaLengkap_label3.setForeground(new java.awt.Color(255, 255, 255));
        namaLengkap_label3.setText("NO TELEPON");
        jPanel1.add(namaLengkap_label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 238, 176, -1));

        alamat.setBorder(null);
        alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alamatActionPerformed(evt);
            }
        });
        jPanel1.add(alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 400, 540, 32));

        namaLengkap_label5.setFont(new java.awt.Font("Oswald", 1, 24)); // NOI18N
        namaLengkap_label5.setForeground(new java.awt.Color(255, 255, 255));
        namaLengkap_label5.setText("ALAMAT");
        jPanel1.add(namaLengkap_label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 276, 176, -1));

        buatTugas.setText("Buat Tugas");
        buatTugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buatTugasActionPerformed(evt);
            }
        });
        jPanel1.add(buatTugas, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 150, 60));

        tambahTugas.setText("Tambah Tugas");
        tambahTugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahTugasActionPerformed(evt);
            }
        });
        jPanel1.add(tambahTugas, new org.netbeans.lib.awtextra.AbsoluteConstraints(573, 70, 160, 60));

        absen.setText("Absen");
        absen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                absenActionPerformed(evt);
            }
        });
        jPanel1.add(absen, new org.netbeans.lib.awtextra.AbsoluteConstraints(863, 70, 120, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/index.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        kembali.setText("jButton2");
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });
        jPanel1.add(kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 20, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buatTugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buatTugasActionPerformed
        
        subPengerjaanTugas st = new subPengerjaanTugas();
        st.show();
        st.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_buatTugasActionPerformed

    private void alamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alamatActionPerformed

    private void noTelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noTelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noTelpActionPerformed

    private void kelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kelasActionPerformed

    private void namaLengkapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaLengkapActionPerformed

    }//GEN-LAST:event_namaLengkapActionPerformed

    private void tambahTugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahTugasActionPerformed
        subTugas st = new subTugas();
        st.show();
        st.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_tambahTugasActionPerformed

    private void absenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_absenActionPerformed

    String proses="INSERT INTO absen_siswa(id_user, tgl) VALUES (?,?)";
    DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd");  
    LocalDateTime now = LocalDateTime.now();  
    System.out.println(dtf.format(now));  
    try {
        Connection conn = (Connection)koneksi.configDB();
        PreparedStatement st=conn.prepareStatement(proses);
        st.setString(1, iduSession);
        st.setString(2, dtf.format(now));


        st.executeUpdate ();
        JOptionPane.showMessageDialog(null, "Data Sukses Disimpan");

    } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "GAGAL DISIMPAN, error di : "+ex);
    }
    
    }//GEN-LAST:event_absenActionPerformed

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        loginMain st = new loginMain();
        st.show();
        st.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_kembaliActionPerformed
    public void test(){
        if(loginMain.getAkses().equals("1")){
            tambahTugas.setVisible(false);
            buatTugas.setVisible(true);
        }else if(loginMain.getAkses().equals("2")){
            tambahTugas.setVisible(true);
            buatTugas.setVisible(false);
            absen.setVisible(false);
        }
    }
    
    public void cekIsi(){
        if(namaLengkap.getText().equals("")){
            namaLengkap.setEnabled(true);
        }else{
            namaLengkap.setEnabled(false);
        }
        if(kelas.getText().equals("")){
            kelas.setEnabled(true);
        }else{
            kelas.setEnabled(false);
        }
        if(noTelp.getText().equals("")){
            noTelp.setEnabled(true);
        }else{
            noTelp.setEnabled(false);
        }
        if(alamat.getText().equals("")){
            alamat.setEnabled(true);
        }else{
            alamat.setEnabled(false);
        }
    }
    
//    public void lihatData() {
//        
//        try{
//            String sql = "select * from user where id_user ='"+loginMain.getId()+"'";             //ngambil data dari mysql
//            Connection conn = koneksi.configDB(); //memanggil koneksi dari file config.java
//            Statement statem = conn.createStatement();       //statement untuk mengexecute query
//            ResultSet result = statem.executeQuery(sql);    //mengambil data dengan memanggil sql
//            while(result.next()){          //perulangan untuk menampilkan data
//                namaLengkap.setText(result.getString("nama_lengkap"));
//                kelas.setText(result.getString("kelas"));
//                umur.setText(result.getString("umur"));
//                noTelp.setText(result.getString("no_telp"));
//                alamat.setText(result.getString("alamat"));;
//                
//            }
//        } catch (SQLException e){
//            JOptionPane.showMessageDialog(null, "Data gagal"+e);
//        }
//        cekIsi();
//    }
    
//    public void ubahData(){
//	     String sql="update user set nama_lengkap=?,kelas=?,umur=? , no_telp=?, alamat=? where id_user='"+loginMain.getId()+"'";
//	     PreparedStatement pr=null;
//	     try {
//                 Connection conn = koneksi.configDB();
//		 pr=conn.prepareStatement (sql);
//		 pr.setString(1,namaLengkap.getText());
//		 pr.setString(2,kelas.getText());
//                 pr.setString(3,umur.getText());
//                 pr.setString(4,noTelp.getText());
//                 pr.setString(5,alamat.getText());
//	      pr.executeUpdate();
//	      JOptionPane.showMessageDialog(null, "Data Berhasil di Ubah");
//	      lihatData();
//	  } catch (SQLException ex){
//		JOptionPane.showMessageDialog(null, "Data gagal"+ex);
//	  }
// }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new index().setVisible(true);
            }
        });
        
    }
    public static String getID(){
        return idSession;
    }
    public static String getIDU(){
        return iduSession;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton absen;
    private javax.swing.JTextField alamat;
    private javax.swing.JButton buatTugas;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField kelas;
    private javax.swing.JButton kembali;
    private javax.swing.JTextField namaLengkap;
    private javax.swing.JLabel namaLengkap_label;
    private javax.swing.JLabel namaLengkap_label2;
    private javax.swing.JLabel namaLengkap_label3;
    private javax.swing.JLabel namaLengkap_label5;
    private javax.swing.JTextField noTelp;
    private javax.swing.JButton tambahTugas;
    private javax.swing.JLabel uname;
    // End of variables declaration//GEN-END:variables
}
