/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loginregisterdb;

/**
 *
 * @author Acer
 */
public class indexAdmin extends javax.swing.JFrame {

    /**
     * Creates new form indexAdmin
     */
    public indexAdmin() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        absen = new javax.swing.JButton();
        tugas = new javax.swing.JButton();
        dataGuru = new javax.swing.JButton();
        dataSiswa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/halaman utama Admin.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        absen.setText("Absen User");
        absen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                absenActionPerformed(evt);
            }
        });
        getContentPane().add(absen, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 280, 160));

        tugas.setText("Daftar Tugas");
        tugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tugasActionPerformed(evt);
            }
        });
        getContentPane().add(tugas, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 230, 290, 170));

        dataGuru.setText("Data Guru");
        dataGuru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataGuruActionPerformed(evt);
            }
        });
        getContentPane().add(dataGuru, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 460, 280, 160));

        dataSiswa.setText("Data Siswa");
        dataSiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataSiswaActionPerformed(evt);
            }
        });
        getContentPane().add(dataSiswa, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 450, 290, 170));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dataGuruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataGuruActionPerformed
        detailGuru dg = new detailGuru();
        dg.show();
        dg.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_dataGuruActionPerformed

    private void dataSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataSiswaActionPerformed
        detailSiswa ds = new detailSiswa();
        ds.show();
        ds.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_dataSiswaActionPerformed

    private void absenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_absenActionPerformed
        detailAbsen da = new detailAbsen();
        da.show();
        da.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_absenActionPerformed

    private void tugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tugasActionPerformed
        detailTugas dt = new detailTugas();
        dt.show();
        dt.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_tugasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(indexAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(indexAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(indexAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(indexAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new indexAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton absen;
    private javax.swing.JButton dataGuru;
    private javax.swing.JButton dataSiswa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton tugas;
    // End of variables declaration//GEN-END:variables
}
