/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loginregisterdb;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.*;

/**
 *
 * @author Acer
 */
public class registerMain extends javax.swing.JFrame {

    /**
     * Creates new form loginMain
     */
    public registerMain() {
        initComponents();
        ButtonGroup bg = new ButtonGroup();
        bg.add(murid);
        bg.add(guru);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        password = new javax.swing.JPasswordField();
        username = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        murid = new javax.swing.JRadioButton();
        guru = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        register = new javax.swing.JButton();
        login = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(51, 102, 255));

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setForeground(new java.awt.Color(51, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        password.setBorder(null);
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        jPanel1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 342, 420, 40));

        username.setBorder(null);
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        jPanel1.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 220, 420, 30));

        jLabel1.setFont(new java.awt.Font("Oswald", 1, 30)); // NOI18N
        jLabel1.setText("REGISTER");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 260, -1));

        murid.setSelected(true);
        murid.setText("Murid");
        jPanel1.add(murid, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 410, 180, -1));

        guru.setText("Guru");
        jPanel1.add(guru, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 410, 160, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/halaman register.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        register.setBackground(new java.awt.Color(204, 255, 255));
        register.setFont(new java.awt.Font("Oswald", 1, 18)); // NOI18N
        register.setForeground(new java.awt.Color(153, 51, 0));
        register.setText("Register");
        register.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 51, 0), 3, true));
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });
        jPanel1.add(register, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 450, 180, 60));

        login.setFont(new java.awt.Font("Oswald", 1, 19)); // NOI18N
        login.setForeground(new java.awt.Color(153, 0, 0));
        login.setText("Login");
        login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginMouseClicked(evt);
            }
        });
        jPanel1.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 540, 180, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseClicked
        /* Kode ini digunakan untuk membuat halaman login muncul (setVisible)
        ketika tulisan register di klik*/
        loginMain log = new loginMain();
        log.show();
        log.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_loginMouseClicked

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        // untuk memanggil method inputData();
        inputData();
    }//GEN-LAST:event_registerActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registerMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            //                new registerMain().setVisible(true);
            registerMain reg = new registerMain();
            reg.setVisible(true);
            reg.setLocationRelativeTo(null);
        });
    }

//Method inputData();
public void inputData(){
    /*Jika text username dan text password kosong maka akan muncul pesan*/
    String status = "murid";
    if(guru.isSelected()){
        status = "guru";
    }
    if(status.equals("murid")){
        if(username.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Mohon Masukan Username");
        }else if(password.getPassword().equals("")){
                JOptionPane.showMessageDialog(null, "Mohon Masukan Password");
        }
        else{
            //String mysql untuk menginputkan username dan password ke tabel user 
            String proses="INSERT INTO user(username,password,akses) VALUES (?,?,?)";
            try {
                //Memanggil koneksi
                Connection conn = (Connection)koneksi.configDB();
                //membuat statement
                PreparedStatement st=conn.prepareStatement(proses);
                //mengisi statement berdasarkan urutan ? pada String mysql diatas
                st.setString(1, username.getText());
                st.setString(2, password.getText());
                st.setString(3, "1");
                //menginputkan data ke database
                st.executeUpdate ();
                //tampilan pesan sukses mentimpan
                JOptionPane.showMessageDialog(null, "Data Sukses Disimpan");
                //jika sukses maka kolom username dan password akan dikosongkan
                username.setText("");
                password.setText("");
            } catch (SQLException ex) {
                //jika input gagal maka akan menampilkan pesan gagal dan errornya    
                JOptionPane.showMessageDialog(null, "GAGAL DISIMPAN, error di : "+ex);
            }
        }
    }else if(status.equals("guru")){
        if(username.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Mohon Masukan Username");
        }else if(password.getPassword().equals("")){
                JOptionPane.showMessageDialog(null, "Mohon Masukan Password");
        }
        else{
            //String mysql untuk menginputkan username dan password ke tabel user 
            String proses="INSERT INTO guru(username,password,akses) VALUES (?,?,?)";
            try {
                //Memanggil koneksi
                Connection conn = (Connection)koneksi.configDB();
                //membuat statement
                PreparedStatement st=conn.prepareStatement(proses);
                //mengisi statement berdasarkan urutan ? pada String mysql diatas
                st.setString(1, username.getText());
                st.setString(2, password.getText());
                st.setString(3, "2");
                //menginputkan data ke database
                st.executeUpdate ();
                //tampilan pesan sukses mentimpan
                JOptionPane.showMessageDialog(null, "Data Sukses Disimpan");
                //jika sukses maka kolom username dan password akan dikosongkan
                username.setText("");
                password.setText("");
            } catch (SQLException ex) {
                //jika input gagal maka akan menampilkan pesan gagal dan errornya    
                JOptionPane.showMessageDialog(null, "GAGAL DISIMPAN, error di : "+ex);
            }
        }
    }
    
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton guru;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel login;
    private javax.swing.JRadioButton murid;
    private javax.swing.JPasswordField password;
    private javax.swing.JButton register;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
