/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loginregisterdb;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Acer
 */
public class subTugas extends javax.swing.JFrame {
    String id = index.getID();
    /**
     * Creates new form subTugas
     */
    public subTugas() {
        initComponents();
        this.setLocationRelativeTo(null);
        idGuru.setText(id);
        idGuru.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        namaTugas = new javax.swing.JTextField();
        tglBerakhir = new javax.swing.JTextField();
        untuk = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        idTugas = new javax.swing.JTextField();
        idGuru = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        clear = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        lihat = new javax.swing.JButton();
        ubah = new javax.swing.JButton();
        tambah = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        namaTugas.setBorder(null);
        getContentPane().add(namaTugas, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 370, 20));

        tglBerakhir.setBorder(null);
        getContentPane().add(tglBerakhir, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 370, 20));

        untuk.setBorder(null);
        getContentPane().add(untuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, 370, 20));

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, 880, 220));

        idTugas.setBorder(null);
        getContentPane().add(idTugas, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 370, 20));

        idGuru.setBorder(null);
        getContentPane().add(idGuru, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 370, 20));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/subTugas.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 430, 130, 40));

        hapus.setText("Hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        getContentPane().add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 210, 260, 60));

        lihat.setText("Lihat Data");
        lihat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lihatActionPerformed(evt);
            }
        });
        getContentPane().add(lihat, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 370, 250, 60));

        ubah.setText("Ubah");
        ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahActionPerformed(evt);
            }
        });
        getContentPane().add(ubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 290, 260, 60));

        tambah.setText("Tambah");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });
        getContentPane().add(tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 130, 250, 60));

        jButton1.setText("Kembali");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 0, 90, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        inputData();
    }//GEN-LAST:event_tambahActionPerformed

    private void ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahActionPerformed
        ubahData();
    }//GEN-LAST:event_ubahActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        hapusData();
    }//GEN-LAST:event_hapusActionPerformed

    private void lihatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lihatActionPerformed
        lihatData();
    }//GEN-LAST:event_lihatActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        idTugas.setText("");
        namaTugas.setText("");
        tglBerakhir.setText("");
        untuk.setText("");
        idTugas.setEnabled(true);
    }//GEN-LAST:event_clearActionPerformed

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        klikData();
    }//GEN-LAST:event_tabelMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        index st = new index();
        st.show();
        st.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(subTugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(subTugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(subTugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(subTugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new subTugas().setVisible(true);
            }
        });
    }
    
    private void lihatData() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID Tugas");
        model.addColumn("ID Guru");
        model.addColumn("Nama Tugas");
        model.addColumn("Tgl Berakhir");
        model.addColumn("Untuk Kelas");
        
        try{
            int no = 1;
            String sql = "select * from tugas";             //ngambil data dari mysql
            Connection conn = (Connection)koneksi.configDB(); //memanggil koneksi dari file config.java
            Statement statem = conn.createStatement();       //statement untuk mengexecute query
            ResultSet result = statem.executeQuery(sql);    //mengambil data dengan memanggil sql
            while(result.next()){          //perulangan untuk menampilkan data
                model.addRow(new Object[]{result.getString(1),result.getString(2),result.getString(3),result.getString(4),result.getString(5)});
            }
            tabel.setModel(model);
            JOptionPane.showMessageDialog(null, "Data berhasil");
        } catch (SQLException e){
            JOptionPane.showMessageDialog(null, "Data gagal");
        }
    }
    
    private void inputData(){
                
		if(namaTugas.getText().equals("")){
			JOptionPane.showMessageDialog(null, "Mohon Masukan judul");
		}else if(tglBerakhir.getText().equals("")){
			JOptionPane.showMessageDialog(null, "Mohon Masukan tanggal");
		}else if(untuk.getText().equals("")){
			JOptionPane.showMessageDialog(null, "Mohon Masukan Kelas");
                }else{
                
		String proses="INSERT INTO tugas(id_tugas,id_guru,nama_tugas,tgl_berakhir,kelas) VALUES (?,?,?,?,?)";
		try {
                    Connection conn = (Connection)koneksi.configDB();
		    PreparedStatement st=conn.prepareStatement(proses);
		    st.setString(1, idTugas.getText());
                    st.setString(2, id);
                    st.setString(3, namaTugas.getText());
		    st.setString(4, tglBerakhir.getText());
		    st.setString(5, untuk.getText());
           
		    
		    st.executeUpdate ();
		    JOptionPane.showMessageDialog(null, "Data Sukses Disimpan");
		    namaTugas.setText("");
                    tglBerakhir.setText("");
		    untuk.setText("");
		    
                    
                    
                    lihatData();
                    
		} catch (SQLException ex) {
			JOptionPane.showMessageDialog(null, "GAGAL DISIMPAN, error di : "+ex);
                }
		}
	}
    private void ubahData(){
	     String sql="update tugas set nama_tugas=?,tgl_berakhir=?,kelas=? where id_tugas="+idTugas.getText();
	     PreparedStatement pr=null;
	     try {
                 Connection conn = (Connection)koneksi.configDB();
		 pr=conn.prepareStatement (sql);
		 pr.setString(1,namaTugas.getText());
		 pr.setString(2,tglBerakhir.getText());
                 pr.setString(3,untuk.getText());
    
	      pr.executeUpdate();
	      JOptionPane.showMessageDialog(null, "Data Berhasil di Ubah");
	      lihatData();
	      
	  } catch (SQLException ex){
		Logger.getLogger(detailSiswa.class.getName()).log(Level.SEVERE,null,ex);
	  }
 }
private void klikData(){
	int baris=tabel.getSelectedRow();
	String a=tabel.getValueAt(baris, 0).toString();
	String b=tabel.getValueAt(baris, 1).toString();
	String c=tabel.getValueAt(baris, 2).toString();
        String d=tabel.getValueAt(baris, 3).toString();
        String e=tabel.getValueAt(baris, 4).toString();
	

	idTugas.setText(a);
        idGuru.setText(b);
	namaTugas.setText(c);
        tglBerakhir.setText(d);
        untuk.setText(e);
    }
private void hapusData(){
	     int cek=JOptionPane.showConfirmDialog(null, "Yakin ingin menghapus ?","Yakin ?",JOptionPane.YES_NO_OPTION);
	     if(cek==0){
		String sql="delete from tugas where id_tugas='"+idTugas.getText()+"'";
		try {
                     Connection conn = (Connection)koneksi.configDB();
		     PreparedStatement pr=conn.prepareStatement (sql);
		     pr.executeUpdate();
		     JOptionPane.showMessageDialog(null, "Berhasil Hapus Data");
		     lihatData();

	      
	  } catch (SQLException ex){
		Logger.getLogger(detailSiswa.class.getName()).log(Level.SEVERE,null,ex);
	  }
     }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clear;
    private javax.swing.JButton hapus;
    private javax.swing.JTextField idGuru;
    private javax.swing.JTextField idTugas;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton lihat;
    private javax.swing.JTextField namaTugas;
    private javax.swing.JTable tabel;
    private javax.swing.JButton tambah;
    private javax.swing.JTextField tglBerakhir;
    private javax.swing.JButton ubah;
    private javax.swing.JTextField untuk;
    // End of variables declaration//GEN-END:variables
}
