/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loginregisterdb;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Acer
 */
public class detailGuru extends javax.swing.JFrame {

    /**
     * Creates new form detailGuru
     */
    public detailGuru() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        id_user = new javax.swing.JTextField();
        password = new javax.swing.JTextField();
        akses = new javax.swing.JTextField();
        nama_lengkap = new javax.swing.JTextField();
        jabatan = new javax.swing.JTextField();
        no_telp = new javax.swing.JTextField();
        alamat = new javax.swing.JTextField();
        username = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        ubah = new javax.swing.JButton();
        lihat = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        tambah = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 130, 625, 520));

        id_user.setBorder(null);
        getContentPane().add(id_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 380, 20));

        password.setBorder(null);
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 380, 20));

        akses.setBorder(null);
        getContentPane().add(akses, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 380, 20));

        nama_lengkap.setBorder(null);
        getContentPane().add(nama_lengkap, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 380, 20));

        jabatan.setBorder(null);
        getContentPane().add(jabatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 440, 380, 20));

        no_telp.setBorder(null);
        getContentPane().add(no_telp, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 490, 380, 20));

        alamat.setBorder(null);
        getContentPane().add(alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 540, 380, 20));

        username.setBorder(null);
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 380, 20));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Tambah data guru dan murid.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 720));

        ubah.setText("Ubah");
        ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahActionPerformed(evt);
            }
        });
        getContentPane().add(ubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 650, 120, 60));

        lihat.setText("Lihat Data");
        lihat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lihatActionPerformed(evt);
            }
        });
        getContentPane().add(lihat, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 650, 160, 50));

        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 590, 110, 50));

        tambah.setText("Tambah");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });
        getContentPane().add(tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 590, 130, 60));

        hapus.setText("Hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        getContentPane().add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 590, 130, 50));

        back.setText("Kembali");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 0, 90, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        klikData();
    }//GEN-LAST:event_tabelMouseClicked

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        inputData();
    }//GEN-LAST:event_tambahActionPerformed

    private void ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahActionPerformed
        ubahData();
    }//GEN-LAST:event_ubahActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        hapusData();
    }//GEN-LAST:event_hapusActionPerformed

    private void lihatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lihatActionPerformed
        lihatData();
    }//GEN-LAST:event_lihatActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        id_user.setText("");
        username.setText("");
        password.setText("");
        akses.setText("");
        nama_lengkap.setText("");
        jabatan.setText("");
        no_telp.setText("");
        alamat.setText("");
        id_user.setEnabled(true);
    }//GEN-LAST:event_clearActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        indexAdmin rm = new indexAdmin();
        rm.show();
        rm.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(detailGuru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(detailGuru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(detailGuru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(detailGuru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new detailGuru().setVisible(true);
            }
        });
    }

    private void lihatData() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("Username");
        model.addColumn("Password");
        model.addColumn("Akses");
        model.addColumn("Nama Lengkap");
        model.addColumn("Jabatan");
        model.addColumn("No Telepon");
        model.addColumn("Alamat");
        
        try{
            int no = 1;
            String sql = "select * from guru";             //ngambil data dari mysql
            Connection conn = (Connection)koneksi.configDB(); //memanggil koneksi dari file config.java
            Statement statem = conn.createStatement();       //statement untuk mengexecute query
            ResultSet result = statem.executeQuery(sql);    //mengambil data dengan memanggil sql
            while(result.next()){          //perulangan untuk menampilkan data
                model.addRow(new Object[]{result.getString(1),result.getString(2),result.getString(3),result.getString(4),result.getString(5),result.getString(6),result.getString(7),result.getString(8)});
            }
            tabel.setModel(model);
            JOptionPane.showMessageDialog(null, "Data berhasil");
        } catch (SQLException e){
            JOptionPane.showMessageDialog(null, "Data gagal");
        }
    }
private void inputData(){
                
		if(id_user.getText().equals("")){
			JOptionPane.showMessageDialog(null, "Mohon Masukan id");
		}else if(username.getText().equals("")){
			JOptionPane.showMessageDialog(null, "Mohon Masukan username");
		}else if(password.getText().equals("")){
			JOptionPane.showMessageDialog(null, "Mohon Masukan Password");
		}else if(akses.getText().equals("")){
			JOptionPane.showMessageDialog(null, "Mohon Masukan akses");
                }else if(nama_lengkap.getText().equals("")){
			JOptionPane.showMessageDialog(null, "Mohon Masukan Nama Lengkap");
                }else if(jabatan.getText().equals("")){
			JOptionPane.showMessageDialog(null, "Mohon Masukan jabatan");
		}else if(no_telp.getText().equals("")){
			JOptionPane.showMessageDialog(null, "Mohon Masukan No Telepon");
                }else if(alamat.getText().equals("")){
			JOptionPane.showMessageDialog(null, "Mohon Masukan Alamat");
                }else{
		String proses="INSERT INTO guru(id_guru,username,password,akses,nama_lengkap,jabatan,no_telp,alamat) VALUES (?,?,?,?,?,?,?,?)";
		try {
                    Connection conn = (Connection)koneksi.configDB();
		    PreparedStatement st=conn.prepareStatement(proses);
		    st.setString(1, id_user.getText());
                    st.setString(2, username.getText());
		    st.setString(3, password.getText());
		    st.setString(4, akses.getText());
                    st.setString(5, nama_lengkap.getText());
                    st.setString(6, jabatan.getText());
		    st.setString(7, no_telp.getText());
                    st.setString(8, alamat.getText());
		    
		    st.executeUpdate ();
		    JOptionPane.showMessageDialog(null, "Data Sukses Disimpan");
		    id_user.setText("");
                    username.setText("");
		    password.setText("");
		    akses.setText("");
                    nama_lengkap.setText("");
                    jabatan.setText("");
		    no_telp.setText("");
		    alamat.setText("");
                    
                    
                    lihatData();
                    
		} catch (SQLException ex) {
			JOptionPane.showMessageDialog(null, "GAGAL DISIMPAN, error di : "+ex);
                }
		}
	}
private void ubahData(){
	     String sql="update guru set username=?,password=?,akses=?,nama_lengkap=?,jabatan=?,no_telp=?,alamat=? where id_guru="+id_user.getText();
	     PreparedStatement pr=null;
	     try {
                 Connection conn = (Connection)koneksi.configDB();
		 pr=conn.prepareStatement (sql);
		 pr.setString(1,username.getText());
		 pr.setString(2,password.getText());
                 pr.setString(3,akses.getText());
                 pr.setString(4,nama_lengkap.getText());
		 pr.setString(5,jabatan.getText());
                 pr.setString(6,no_telp.getText());
                 pr.setString(7,alamat.getText());
	      pr.executeUpdate();
	      JOptionPane.showMessageDialog(null, "Data Berhasil di Ubah");
	      lihatData();
	      
	  } catch (SQLException ex){
		Logger.getLogger(detailSiswa.class.getName()).log(Level.SEVERE,null,ex);
	  }
 }
private void klikData(){
	int baris=tabel.getSelectedRow();
	String a=tabel.getValueAt(baris, 0).toString();
	String b=tabel.getValueAt(baris, 1).toString();
	String c=tabel.getValueAt(baris, 2).toString();
        String d=tabel.getValueAt(baris, 3).toString();
        String e=tabel.getValueAt(baris, 4).toString();
	String f=tabel.getValueAt(baris, 5).toString();
	String g=tabel.getValueAt(baris, 6).toString();
        String h=tabel.getValueAt(baris, 7).toString();

	id_user.setText(a);
	username.setText(b);
        password.setText(c);
        akses.setText(d);
        nama_lengkap.setText(e);
	jabatan.setText(f);
        no_telp.setText(g);
        alamat.setText(h);
        id_user.setEnabled(false);
    }
private void hapusData(){
	     int cek=JOptionPane.showConfirmDialog(null, "Yakin ingin menghapus ?","Yakin ?",JOptionPane.YES_NO_OPTION);
	     if(cek==0){
		String sql="delete from guru where id_guru='"+id_user.getText()+"'";
		try {
                     Connection conn = (Connection)koneksi.configDB();
		     PreparedStatement pr=conn.prepareStatement (sql);
		     pr.executeUpdate();
		     JOptionPane.showMessageDialog(null, "Berhasil Hapus Data");
		     lihatData();

	      
	  } catch (SQLException ex){
		Logger.getLogger(detailSiswa.class.getName()).log(Level.SEVERE,null,ex);
	  }
     }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField akses;
    private javax.swing.JTextField alamat;
    private javax.swing.JButton back;
    private javax.swing.JButton clear;
    private javax.swing.JButton hapus;
    private javax.swing.JTextField id_user;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jabatan;
    private javax.swing.JButton lihat;
    private javax.swing.JTextField nama_lengkap;
    private javax.swing.JTextField no_telp;
    private javax.swing.JTextField password;
    private javax.swing.JTable tabel;
    private javax.swing.JButton tambah;
    private javax.swing.JButton ubah;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
